ConvMe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Converter.urls')),
]

Converter/urls.py
from django.contrib import admin
from django.urls import path
from Converter import views

app_name = 'Converter'

urlpatterns = [
    path('', views.index, name='index'),
    path('convLength', views.convLength, name='convLength'),
    path('convWeight', views.convWeight, name='convWeight'),
    path('convVolume', views.convVolume, name='convVolume'),
    path('convCurrency', views.convCurrency, name='convCurrency')
]

Converter/models.py
from django.db import models

# Create your models here.

Converter/views.py
from django.shortcuts import render
from django.http import JsonResponse
# Create your views here.
def index(request):
    return render(request, 'Converter/index.html', context={'lenResult': '', 'wgtResult':'', 'volResult':'', 'curResult':''})

def convLength(request):
    if(request.method == 'POST'):
        src = request.POST['src']
        dest = request.POST['dest']
        num = request.POST['val']
        num = float(num)
        res = num
        if(src == 'src-feet' and dest == 'dest-feet'):
            res = num
        if(src == 'src-feet' and dest == 'dest-inch'):
            res = num*12
        if(src == 'src-feet' and dest == 'dest-metre'):
            res = num/3.3
        if(src == 'src-inch' and dest == 'dest-feet'):
            res = num/12
        if(src == 'src-inch' and dest == 'dest-inch'):
            res = num
        if(src == 'src-inch' and dest == 'dest-metre'):
            res = num*0.0254
        if(src == 'src-metre' and dest == 'dest-feet'):
            res = num*3.3
        if(src == 'src-metre' and dest == 'dest-inch'):
            res = num*39.37
        if(src == 'src-metre' and dest == 'dest-metre'):
            res = num
        return JsonResponse({'res': res})

def convWeight(request):
    if(request.method == 'POST'):
        src = request.POST.get('src-weight-radio')
        dest = request.POST.get('dest-weight-radio')
        num = request.POST.get('src-weight')
        num = int(num)
        res = num
        if(src == 'src-pound' and dest == 'dest-pound'):
            res = num
        if(src == 'src-pound' and dest == 'dest-kg'):
            res = num*0.4535
        if(src == 'src-kg' and dest == 'dest-pound'):
            res = num*2.204
        if(src == 'src-kg' and dest == 'dest-kg'):
            res = num
        return render(request, 'Converter/index.html', context={'lenResult': '', 'wgtResult':str(res), 'volResult':'', 'curResult':''})

def convVolume(request):
    if(request.method == 'POST'):
        src = request.POST.get('src-vol-radio')
        dest = request.POST.get('dest-vol-radio')
        num = request.POST.get('src-vol')
        num = int(num)
        res = num
        if(src == 'src-cuMt' and dest == 'dest-cuMt'):
            res = num
        if(src == 'src-cuMt' and dest == 'dest-l'):
            res = num*1000
        if(src == 'src-l' and dest == 'dest-cuMt'):
            res = num/1000
        if(src == 'src-l' and dest == 'dest-l'):
            res = num
        return render(request, 'Converter/index.html', context={'lenResult': '', 'wgtResult':'', 'volResult':str(res), 'curResult':''})

def convCurrency(request):
    if(request.method == 'POST'):
        src = request.POST.get('src-cur-radio')
        dest = request.POST.get('dest-cur-radio')
        num = request.POST.get('src-cur')
        num = int(num)
        res = num
        if(src == 'src-dollar' and dest == 'dest-dollar'):
            res = num
        if(src == 'src-dollar' and dest == 'dest-rupee'):
            res = num*67.659
        if(src == 'src-rupee' and dest == 'dest-dollar'):
            res = num/67.659
        if(src == 'src-rupee' and dest == 'dest-rupee'):
            res = num
        return render(request, 'Converter/index.html', context={'lenResult': '', 'wgtResult':'', 'volResult':'', 'curResult':str(res)})

Converter/templates/Converter/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Conv Me{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'Converter/base.css' %}">
  {% block appstaticfiles %}{% endblock %}
</head>
<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light text-primary">
    <a class="navbar-brand" href="#">Conv Me</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item" id="nav-length">
          <a class="nav-link" href="#length">Length</a>
        </li>
        <li class="nav-item" id="nav-weight">
          <a class="nav-link" href="#weight">Weight</a>
        </li>
        <li class="nav-item" id="nav-volume">
          <a class="nav-link" href="#volume">Volume</a>
        </li>
        <li class="nav-item" id="nav-currency">
          <a class="nav-link" href="#currency">Currency</a>
        </li>
      </ul>
    </div>
  </nav>
  <main class="container-fluid d-flex flex-column justify-content-center align-items-center text-light">
    <h1 class="display-3">Welcome to Conv Me!</h1>
    <p>Your one-stop Unit Conversion tool</p>
  </main>
  {% block content %}
  {% endblock %}
  <footer class="bg-secondary text-light d-flex flex-column justify-content-center align-items-center">
    Copyrights &copy; 2018-20 Conv Me Inc. All Rights Reserved.
  </footer>
  {% block javascript %}
  {% endblock %}
  <script type="text/javascript">
  $(function() {
    console.log($("nav").outerHeight());
    // This function gets cookie with a given name
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    /*
    The functions below will create a header with csrftoken
    */

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    function sameOrigin(url) {
        // test that a given url is a same-origin URL
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                // Send the token to same-origin, relative URLs only.
                // Send the token only if the method warrants CSRF protection
                // Using the CSRFToken value acquired earlier
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

  });
  </script>
</body>
</html>

Converter/templates/Converter/index.html
{% extends 'Converter/base.html' %}

{% block appstaticfiles %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'Converter/index.css' %}">
{% endblock %}

{% block content %}
<div class="convert-type p-5" id="length">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <img src="{% static 'Converter/length.png' %}" alt="length" width="50%">
        <h1 class="display-4">Length</h1>
      </div>
      <div class="col-lg-7">
        <form class="form" ajaxUrl="{% url 'Converter:convLength' %}" id="len-form" method="post">
          {% csrf_token %}
          <fieldset class="form-group">
            <h5>Source</h5>
            <input type="radio" name="src-length-radio" value="src-feet" id="src-length-feet">
            <label for="src-length-feet"> Feet</label>
            <input type="radio" name="src-length-radio" value="src-inch" id="src-length-inch">
            <label for="src-length-inch"> Inch</label>
            <input type="radio" name="src-length-radio" value="src-metre" id="src-length-metre">
            <label for="src-length-meter"> Metre</label>
          </fieldset>
          <fieldset class="form-group">
            <h5>Destination</h5>
            <input type="radio" name="dest-length-radio" value="dest-feet" id="dest-length-feet">
            <label for="dest-length-feet"> Feet</label>
            <input type="radio" name="dest-length-radio" value="dest-inch" id="dest-length-inch">
            <label for="dest-length-inch"> Inch</label>
            <input type="radio" name="dest-length-radio" value="dest-metre" id="dest-length-metre">
            <label for="dest-length-meter"> Metre</label>
          </fieldset>
          <div class="form-group">
            <input type="number" step="any" class="form-control" name="src-length" id="src-length" placeholder="Enter Value">
          </div>
          <button type="submit" class="btn btn-outline-primary btn-lg">Convert</button>
        </form>
        <br>
        <p class="lead" id="lenResult"></p>
      </div>
    </div>
  </div>
</div>
<div class="convert-type p-5" id="weight">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <img src="{% static 'Converter/weight.png' %}" alt="weight" width="50%">
        <h1 class="display-4">Weight</h1>
      </div>
      <div class="col-lg-7">
        <form class="form" action="{% url 'Converter:convWeight' %}" method="post">
          {% csrf_token %}
          <fieldset class="form-group">
            <h5>Source</h5>
            <input type="radio" name="src-weight-radio" value="src-pound">
            <label for="src-length-feet"> Pound</label>
            <input type="radio" name="src-weight-radio" value="src-kg">
            <label for="src-length-inch"> Kg</label>
          </fieldset>
          <fieldset class="form-group">
            <h5>Destination</h5>
            <input type="radio" name="dest-weight-radio" value="dest-pound">
            <label for="dest-length-feet"> Pound</label>
            <input type="radio" name="dest-weight-radio" value="dest-kg">
            <label for="dest-length-inch"> Kg</label>
          </fieldset>
          <div class="form-group">
            <input type="number" class="form-control" name="src-weight" id="src-weight" placeholder="Enter Value">
          </div>
          <button type="submit" class="btn btn-outline-primary btn-lg">Convert</button>
        </form>
        {% if wgtResult != '' %}
        <h1>Converted: {{ wgtResult }}</h1>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<div class="convert-type p-5" id="volume">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <img src="{% static 'Converter/volume.png' %}" alt="volume" width="50%">
        <h1 class="display-4">Volume</h1>
      </div>
      <div class="col-lg-7">
        <form class="form" action="{% url 'Converter:convVolume' %}" method="post">
          {% csrf_token %}
          <fieldset class="form-group">
            <h5>Source</h5>
            <input type="radio" name="src-vol-radio" value="src-cuMt">
            <label for="src-length-feet"> Cubic Metre</label>
            <input type="radio" name="src-vol-radio" value="src-l">
            <label for="src-length-inch"> Litre</label>
          </fieldset>
          <fieldset class="form-group">
            <h5>Destination</h5>
            <input type="radio" name="dest-vol-radio" value="dest-cuMt">
            <label for="dest-length-feet"> Cubic Metre</label>
            <input type="radio" name="dest-vol-radio" value="dest-l">
            <label for="dest-length-inch"> Litre</label>
          </fieldset>
          <div class="form-group">
            <input type="number" class="form-control" name="src-vol" id="src-vol" placeholder="Enter Value">
          </div>
          <button type="submit" class="btn btn-outline-primary btn-lg">Convert</button>
        </form>
        {% if volResult != '' %}
        <h1>Converted: {{ volResult }}</h1>
        {% endif %}
      </div>
    </div>
  </div>
</div>
<div class="convert-type p-5" id="currency">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <img src="{% static 'Converter/currency.png' %}" alt="currency" width="50%">
        <h1 class="display-4">Currency</h1>
      </div>
      <div class="col-lg-7">
        <form class="form" action="{% url 'Converter:convCurrency' %}" method="post">
          {% csrf_token %}
          <fieldset class="form-group">
            <h5>Source</h5>
            <input type="radio" name="src-cur-radio" value="src-dollar">
            <label for="src-length-feet"> Dollar</label>
            <input type="radio" name="src-cur-radio" value="src-rupee">
            <label for="src-length-inch"> Rupee</label>
          </fieldset>
          <fieldset class="form-group">
            <h5>Destination</h5>
            <input type="radio" name="dest-cur-radio" value="dest-dollar">
            <label for="dest-length-feet"> Dollar</label>
            <input type="radio" name="dest-cur-radio" value="dest-rupee">
            <label for="dest-length-inch"> Rupee</label>
          </fieldset>
          <div class="form-group">
            <input type="number" class="form-control" name="src-cur" id="src-cur" placeholder="Enter Value">
          </div>
          <button type="submit" class="btn btn-outline-primary btn-lg">Convert</button>
        </form>
        {% if curResult != '' %}
        <h1>Converted: {{ curResult }}</h1>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
  $(function() {
    $('#len-form').submit(function(e) {
      e.preventDefault();
      console.log('Submit through my Ajax Function.');
      $.ajax({
        type: 'POST',
        url: $(this).attr('ajaxUrl'),
        data: {
          src: $('input[name=src-length-radio]:checked').val(),
          dest: $('input[name=dest-length-radio]:checked').val(),
          val: $('input[name=src-length]').val(),
        },
        success: function(responseData) {
          console.log("result: " + responseData.res);
          $('#lenResult').text("Converted: " + responseData.res);
          $('#wgtResult').text("");
          $('#volResult').text("");
          $('#curResult').text("");
        }
      });
    });
    
  });
</script>
{% endblock %}